-- script for establishing database of Tikaj project

CREATE SCHEMA IF NOT EXISTS TIKAJ;

USE TIKAJ;

CREATE TABLE IF NOT EXISTS MATERIAL
(
    ID UUID PRIMARY KEY,
    UNIT VARCHAR(15) NOT NULL CHECK (UNIT IN ( 'SQUARE_METER','PIECE','GRAM','MILLILITER','MINUTE','HOUR')),
    UNIT_PRICE DECFLOAT(2),
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    CREATED TIMESTAMP NOT NULL,
    EDITED TIMESTAMP,
);

